### PR TITLE
Pusher release 1.1.8

### PR DESCRIPTION
**Pull request by BenPope**

### CODE REVIEW

**Comment by BenPope** [comment]
[[1] Istio 1.1: Update to latest 1.1.x before staging/production](https://trello.com/c/ahAQOOxn/1135-1-istio-11-update-to-latest-11x-before-staging-production)

**Comment by BenPope** [comment]
[[0.5] Istio 1.1: Fix dry-run](https://trello.com/c/rxCjRuqP/1136-05-istio-11-fix-dry-run)

**Review by samuelyallop-pusher — APPROVED** [review]

**Pull request closed without merging**
